services:
  ollama:
    build:
      context: .
      dockerfile: DockerFile
    image: my-ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - default
      
  openWebUi:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      - default
    depends_on:
      - ollama

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=$NGROK_TOKEN
    ports:
      - "4040:4040"
    command: ["http", "open-webui:8080"]
    networks:
      - default
    depends_on:
      - openWebUi

volumes:
  ollama_data:
  open_webui_data:
networks:
  default:
